/**
 * KisanSathi Hosted Central Catalog Service
 * -------------------------------------------------------------
 * Represents the cloud server database populated by the n8n + Apify web scrapers.
 * Contains common reference datasets:
 *  1. Live Agmarknet APMC Mandi commodity rates
 *  2. Farm Machinery & Tractor Rental Discovery catalog
 *  3. Fertilizer technical specs & subsidized MRP directory
 *  4. Certified Seed Varieties
 *  5. Central & State Government Schemes (PM-KISAN, PMFBY, MahaDBT, PM-KUSUM)
 */

export const HOSTED_MANDI_PRICES = [
  {
    id: 'm1',
    mandi: 'Pune APMC (Market Yard)',
    mandiMr: 'पुणे कृषी उत्पन्न बाजार समिती (मार्केट यार्ड)',
    mandiHi: 'पुणे एपीएमसी (मार्केट यार्ड)',
    district: 'Pune',
    state: 'Maharashtra',
    commodity: 'Wheat (Lokwan / Sharbati)',
    modalPrice: 2125,
    minPrice: 2050,
    maxPrice: 2280,
    changePct: '+2.35%',
    trend: 'up',
    arrivalTodayQtl: 1450,
    distanceKm: 14,
    lastScraped: 'Today, 05:30 AM',
  },
  {
    id: 'm2',
    mandi: 'Baramati APMC',
    mandiMr: 'बारामती बाजार समिती',
    mandiHi: 'बारामती एपीएमसी',
    district: 'Pune',
    state: 'Maharashtra',
    commodity: 'Wheat (Lokwan / Sharbati)',
    modalPrice: 2150,
    minPrice: 2080,
    maxPrice: 2310,
    changePct: '+2.60%',
    trend: 'up',
    arrivalTodayQtl: 920,
    distanceKm: 78,
    lastScraped: 'Today, 05:30 AM',
  },
  {
    id: 'm3',
    mandi: 'Shirur Mandi',
    mandiMr: 'शिरूर बाजार समिती',
    mandiHi: 'शिरूर मंडी',
    district: 'Pune',
    state: 'Maharashtra',
    commodity: 'Wheat (Lokwan / Sharbati)',
    modalPrice: 2080,
    minPrice: 2000,
    maxPrice: 2190,
    changePct: '+1.85%',
    trend: 'up',
    arrivalTodayQtl: 1100,
    distanceKm: 64,
    lastScraped: 'Today, 05:30 AM',
  },
  {
    id: 'm4',
    mandi: 'Daund Mandi',
    mandiMr: 'दौंड बाजार समिती',
    mandiHi: 'दौंड मंडी',
    district: 'Pune',
    state: 'Maharashtra',
    commodity: 'Wheat (Lokwan / Sharbati)',
    modalPrice: 2050,
    minPrice: 1980,
    maxPrice: 2140,
    changePct: '+1.20%',
    trend: 'up',
    arrivalTodayQtl: 750,
    distanceKm: 82,
    lastScraped: 'Today, 05:30 AM',
  },
  {
    id: 'm5',
    mandi: 'Narayangaon Mandi',
    mandiMr: 'नारायणगाव उपबाजार',
    mandiHi: 'नारायणगांव मंडी',
    district: 'Pune',
    state: 'Maharashtra',
    commodity: 'Wheat (Lokwan / Sharbati)',
    modalPrice: 2110,
    minPrice: 2040,
    maxPrice: 2240,
    changePct: '+1.40%',
    trend: 'up',
    arrivalTodayQtl: 890,
    distanceKm: 75,
    lastScraped: 'Today, 05:30 AM',
  },
  {
    id: 'm6',
    mandi: 'Lasalgaon Mandi (Nashik)',
    mandiMr: 'लासलगाव बाजार समिती (नाशिक)',
    mandiHi: 'लासलगांव मंडी (नासिक)',
    district: 'Nashik',
    state: 'Maharashtra',
    commodity: 'Onion (Red)',
    modalPrice: 1850,
    minPrice: 1400,
    maxPrice: 2250,
    changePct: '+4.10%',
    trend: 'up',
    arrivalTodayQtl: 4200,
    distanceKm: 185,
    lastScraped: 'Today, 05:30 AM',
  },
];

export const HOSTED_MACHINERY_RENTALS = [
  {
    id: 'mach-1',
    name: 'Mahindra 575 DI (45 HP Tractor)',
    nameMr: 'महिंद्रा ५७५ DI (४५ HP ट्रॅक्टर)',
    nameHi: 'महिन्द्रा 575 DI (45 HP ट्रैक्टर)',
    category: 'Tractor',
    categoryMr: 'ट्रॅक्टर',
    categoryHi: 'ट्रैक्टर',
    hp: '45 HP',
    implementsIncluded: 'Trolley + 9-Tyne Cultivator',
    hourlyRate: 850,
    dailyRate: 4800,
    ownerName: 'Vilas Patil',
    village: 'Hadapsar / Manjri, Pune',
    distanceKm: 6.2,
    phone: '+91 98221 45012',
    rating: 4.9,
    reviewsCount: 38,
    availableStatus: 'Available Today',
    availableStatusMr: 'आज उपलब्ध',
    availableStatusHi: 'आज उपलब्ध',
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'mach-2',
    name: 'John Deere 5050 D 4WD (50 HP)',
    nameMr: 'जॉन डीअर ५०५० D 4WD (५० HP)',
    nameHi: 'जॉन डियर 5050 D (50 HP)',
    category: 'Tractor',
    categoryMr: 'ट्रॅक्टर',
    categoryHi: 'ट्रैक्टर',
    hp: '50 HP',
    implementsIncluded: 'Heavy Duty 2-MB Reversible Plough',
    hourlyRate: 1100,
    dailyRate: 6200,
    ownerName: 'Sanjay Deshmukh',
    village: 'Wagholi / Loni Kalbhor, Pune',
    distanceKm: 11.4,
    phone: '+91 94220 89123',
    rating: 4.8,
    reviewsCount: 42,
    availableStatus: 'Available Tomorrow',
    availableStatusMr: 'उद्या उपलब्ध',
    availableStatusHi: 'कल उपलब्ध',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'mach-3',
    name: 'Shaktiman 7-Feet Rotary Tiller (Rotavator)',
    nameMr: 'शक्तिमान ७-फूट रोटाव्हेटर',
    nameHi: 'शक्तिमान 7-फीट रोटावेटर',
    category: 'Implements',
    categoryMr: 'मशागत अवजारे',
    categoryHi: 'जुताई उपकरण',
    hp: 'Requires 40+ HP Tractor',
    implementsIncluded: 'Boron Steel Blades (Fine Soil Pulverization)',
    hourlyRate: 500,
    dailyRate: 2800,
    ownerName: 'Kiran Shinde',
    village: 'Uruli Kanchan, Pune',
    distanceKm: 18.0,
    phone: '+91 97654 32189',
    rating: 4.95,
    reviewsCount: 56,
    availableStatus: 'Available Today',
    availableStatusMr: 'आज उपलब्ध',
    availableStatusHi: 'आज उपलब्ध',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'mach-4',
    name: 'Preet 987 Self-Propelled Combine Harvester',
    nameMr: 'प्रीत ९८७ कम्बाइन हार्वेस्टर (धान्य काढणी यंत्र)',
    nameHi: 'प्रीत 987 कंबाइन हार्वेस्टर',
    category: 'Harvester',
    categoryMr: 'काढणी यंत्र',
    categoryHi: 'कंबाइन हार्वेस्टर',
    hp: '101 HP Heavy Harvester',
    implementsIncluded: 'Wheat & Grain Cutting + Threshing + Bagging',
    hourlyRate: 1800,
    dailyRate: 14500,
    ownerName: 'Ganesh Shingate Agro Services',
    village: 'Shirur / Saswad, Pune',
    distanceKm: 24.5,
    phone: '+91 98810 56789',
    rating: 4.7,
    reviewsCount: 64,
    availableStatus: 'Booking for Harvest Season',
    availableStatusMr: 'काढणी हंगामासाठी बुकिंग सुरू',
    availableStatusHi: 'कटाई सीजन बुकिंग चालू',
    image: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'mach-5',
    name: 'Kisan Agriculture Drone Spraying Unit (16L)',
    nameMr: 'किसान कृषी ड्रोन फवारणी युनिट (१६ लिटर)',
    nameHi: 'किसान कृषि ड्रोन छिड़काव यूनिट (16L)',
    category: 'Drone',
    categoryMr: 'कृषी ड्रोन',
    categoryHi: 'कृषि ड्रोन',
    hp: 'DGCA Certified Pilot + Drone',
    implementsIncluded: 'Ultra-Low Volume (ULV) Micron Spraying (10 mins/acre)',
    hourlyRate: 450,
    dailyRate: 450, // Per acre basis
    ownerName: 'SkyAgri Drone Hub Pune',
    village: 'Pune Rural Hub (Coverage within 50 km)',
    distanceKm: 8.0,
    phone: '+91 88001 23456',
    rating: 4.9,
    reviewsCount: 89,
    availableStatus: 'Instant Slot Available',
    availableStatusMr: 'त्वरित स्लॉट उपलब्ध',
    availableStatusHi: 'तुरंत स्लॉट उपलब्ध',
    image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'mach-6',
    name: 'Multi-Crop High Output Thresher',
    nameMr: 'मल्टी-क्रॉप थ्रेशर (मळणी यंत्र)',
    nameHi: 'मल्टी-क्रॉप थ्रेशर मशीन',
    category: 'Thresher',
    categoryMr: 'मळणी यंत्र',
    categoryHi: 'थ्रेशर',
    hp: '35 HP PTO Powered',
    implementsIncluded: 'Threshes Wheat, Gram, Mustard, Soybean',
    hourlyRate: 650,
    dailyRate: 3600,
    ownerName: 'Baburao Jagtap',
    village: 'Bhor / Khed Shivapur, Pune',
    distanceKm: 28.0,
    phone: '+91 99214 77890',
    rating: 4.8,
    reviewsCount: 29,
    availableStatus: 'Available Today',
    availableStatusMr: 'आज उपलब्ध',
    availableStatusHi: 'आज उपलब्ध',
    image: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80',
  },
];

export const HOSTED_FERTILIZERS_DIRECTORY = [
  {
    id: 'f1',
    name: 'IFFCO Neem Coated Urea (46% N)',
    nameMr: 'इफको नीम कोटेड युरिया (४६% नत्र)',
    nameHi: 'इफको नीम कोटेड यूरिया',
    type: 'Nitrogenous Fertilizer',
    bagSize: '45 kg Bag',
    subsidizedMrp: 266.5,
    govtSubsidyPerBag: 2184.0,
    dosagePerAcre: '40–45 kg per split dose at CRI and Tillering stage',
    suitableCrops: ['Wheat', 'Paddy', 'Sugarcane', 'Cotton', 'Maize'],
  },
  {
    id: 'f2',
    name: 'IFFCO DAP (18-46-0)',
    nameMr: 'इफको डीएपी (१८-४६-० डाय-अमोनियम फॉस्फेट)',
    nameHi: 'इफको डीएपी (18-46-0)',
    type: 'Phosphatic Fertilizer',
    bagSize: '50 kg Bag',
    subsidizedMrp: 1350.0,
    govtSubsidyPerBag: 2500.0,
    dosagePerAcre: '50 kg at basal sowing time',
    suitableCrops: ['Wheat', 'Potato', 'Mustard', 'Soybean', 'Pulses'],
  },
  {
    id: 'f3',
    name: 'MOP - Muriate of Potash (60% K2O)',
    nameMr: 'म्युरिएट ऑफ पोटॅश (६०% पालाश)',
    nameHi: 'म्यूरिएट ऑफ पोटाश (MOP 60%)',
    type: 'Potassic Fertilizer',
    bagSize: '50 kg Bag',
    subsidizedMrp: 1650.0,
    govtSubsidyPerBag: 750.0,
    dosagePerAcre: '25–30 kg per acre for grain luster and drought tolerance',
    suitableCrops: ['Wheat', 'Sugarcane', 'Potato', 'Fruits', 'Vegetables'],
  },
];

export const HOSTED_SEED_VARIETIES = [
  {
    id: 's1',
    crop: 'Wheat',
    variety: 'HD-2967 (Pusa Wheat)',
    durationDays: '125–135 Days',
    yieldPotential: '24–28 Quintals / Acre',
    diseaseResistance: 'High resistance to Yellow and Brown Rust',
    recommendedZone: 'North Western and Central Plains (Maharashtra/MP/Punjab)',
  },
  {
    id: 's2',
    crop: 'Wheat',
    variety: 'GW-322 (Sharbati Gold)',
    durationDays: '115–125 Days',
    yieldPotential: '22–26 Quintals / Acre',
    diseaseResistance: 'Heat tolerant, optimal for Central Zone',
    recommendedZone: 'Maharashtra, Gujarat, Madhya Pradesh',
  },
];
