import { Leaf, MapPin } from 'lucide-react';
import ConversationView from '../components/features/ai/ConversationView.jsx';
import { useAIConversation } from '../context/AIConversationContext.jsx';

const questions = { en: ['When should I irrigate my crop?', 'What does my latest soil reading show?', 'Why is there an alert on my field?'], hi: ['मेरी फसल में सिंचाई कब करूं?', 'मिट्टी की नवीनतम जांच क्या बताती है?', 'मेरे खेत में चेतावनी क्यों है?'], mr: ['माझ्या पिकाला सिंचन कधी करावे?', 'मातीच्या शेवटच्या तपासणीत काय दिसते?', 'माझ्या शेतावर सूचना का आली आहे?'] };

export default function AIAssistant() {
  const { language, fields, selectedField, selectedFieldId, setSelectedFieldId, sendText } = useAIConversation();
  const suggestions = questions[language] || questions.en;
  return <div className="mx-auto flex min-h-[calc(100svh-68px)] max-w-[1440px] flex-col gap-5 bg-background px-4 py-5 sm:px-6 lg:flex-row lg:px-8"><aside className="hidden w-72 shrink-0 rounded-card border border-border bg-white p-5 shadow-card lg:block"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-primary text-white"><Leaf size={19} /></span><div><p className="font-bold">KisanSathi Advisor</p><p className="text-[11px] text-text-secondary">Backend-connected assistant</p></div></div><div className="mt-6 rounded-xl border border-border p-4"><p className="text-xs font-bold uppercase tracking-wide text-text-muted">Selected field</p><select value={selectedFieldId} onChange={(event) => setSelectedFieldId(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-white p-2 text-sm">{fields.map((field) => <option value={field.id} key={field.id}>{field.name}</option>)}</select><p className="mt-3 flex items-center gap-1 text-xs text-text-secondary"><MapPin size={13} />{selectedField?.name || 'No field selected'}</p></div><p className="mt-6 text-xs leading-5 text-text-secondary">Responses are returned by the configured provider and retain citations when available. No local answer is invented when the provider is unavailable.</p></aside><section className="flex min-h-[600px] min-w-0 flex-1 flex-col"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Ask KisanSathi</h1><p className="mt-1 text-sm text-text-secondary">Ask about {selectedField?.name || 'your recorded farm data'}.</p></div><select value={selectedFieldId} onChange={(event) => setSelectedFieldId(event.target.value)} className="rounded-lg border border-border bg-white px-3 py-2 text-sm lg:hidden">{fields.map((field) => <option value={field.id} key={field.id}>{field.name}</option>)}</select></div><div className="mb-3 flex flex-wrap gap-2">{suggestions.map((question) => <button key={question} onClick={() => sendText(question)} className="rounded-lg border border-primary/20 bg-primary-50 px-3 py-2 text-xs font-medium text-primary">{question}</button>)}</div><ConversationView /></section></div>;
}
