import { useEffect, useMemo, useState } from 'react';
import { Camera, CheckCircle2, ChevronRight, List, ScanSearch, Sprout, Upload, Wheat } from 'lucide-react';
import { Link } from 'react-router-dom';
import { farmStateApi } from '../api/farmStateApi.js';
import { useFarmData } from '../context/FarmDataContext.jsx';
import { EmptyState, ErrorState, LoadingState, SourceStamp } from '../components/feedback/ApiState.jsx';

const Card = ({ children, className = '' }) => <section className={`rounded-card border border-border bg-white p-5 shadow-card ${className}`}>{children}</section>;
const Page = ({ title, subtitle, children }) => <div className="mx-auto max-w-[1440px] px-4 py-5 sm:px-6 lg:px-8 lg:py-7"><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-text-secondary">{subtitle}</p><div className="mt-6">{children}</div></div>;

function boundaryCoordinates(boundary) { const geometry = boundary?.geometry || boundary; const polygons = geometry?.type === 'MultiPolygon' ? geometry.coordinates.map((polygon) => polygon[0]) : [geometry?.coordinates?.[0] || []]; return polygons; }
function GeoMap({ fields, selected, onSelect }) {
  const points = useMemo(() => {
    const all = fields.flatMap((field) => boundaryCoordinates(field.boundary_geojson).flat()).filter((point) => point.length >= 2);
    if (!all.length) return {};
    const xs = all.map((point) => point[0]);
    const ys = all.map((point) => point[1]);
    const minX = Math.min(...xs);
    const maxX = Math.max(...xs);
    const minY = Math.min(...ys);
    const maxY = Math.max(...ys);
    return Object.fromEntries(fields.map((field) => [
      field.id,
      boundaryCoordinates(field.boundary_geojson).map((polygon) => polygon.map(([x, y]) => [
        20 + ((x - minX) / Math.max(maxX - minX, 0.0001)) * 560,
        390 - ((y - minY) / Math.max(maxY - minY, 0.0001)) * 340,
      ].join(',')).join(' ')),
    ]));
  }, [fields]);
  return <div className="relative min-h-[430px] overflow-hidden rounded-card border border-border bg-[linear-gradient(135deg,#6a7a39,#9eae61_45%,#c9a76b_46%,#7e963e_70%,#b8ca7a)] shadow-card"><svg viewBox="0 0 620 430" className="absolute inset-0 h-full w-full" role="img" aria-label="Farm map"><defs><pattern id="fieldGrid" width="55" height="55" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><path d="M 0 0 L 0 55" stroke="white" strokeOpacity=".17" strokeWidth="2" /></pattern></defs><rect width="620" height="430" fill="url(#fieldGrid)" pointerEvents="none" />{fields.map((field) => <g key={field.id} onClick={() => onSelect(field)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onSelect(field); }} role="button" tabIndex="0" aria-label={`Select ${field.name}`} pointerEvents="bounding-box" className="cursor-pointer"><polygon points={points[field.id]?.[0] || '80,80 180,80 180,160 80,160'} fill={field.id === selected?.id ? '#1f6f36' : '#2e7d32'} fillOpacity=".78" stroke="white" strokeWidth={field.id === selected?.id ? 5 : 2} /><text x="130" y="120" fill="white" textAnchor="middle" fontSize="13">{field.name}</text></g>)}</svg><p className="absolute bottom-4 left-4 rounded-lg bg-black/45 px-3 py-2 text-xs text-white">Backend GeoJSON · select a field</p></div>;
}

export function FarmMap() {
  const { mapFields, fields, loading, error, refresh } = useFarmData(); const [selected, setSelected] = useState(null); const [mode, setMode] = useState('map'); const list = mapFields.length ? mapFields : fields; const activeSelected = selected || list[0];
  return <Page title="My Farm Map" subtitle="View the status of every field from recorded boundaries and observations.">{loading ? <LoadingState /> : error ? <ErrorState error={error} onRetry={refresh} /> : !list.length ? <EmptyState title="No mapped fields" detail="Create a field with a location before opening the farm map." /> : <><div className="mb-5 inline-flex rounded-lg bg-surface-muted p-1"><button onClick={() => setMode('map')} className={mode === 'map' ? 'rounded-md bg-primary px-4 py-2 text-xs font-semibold text-white' : 'rounded-md px-4 py-2 text-xs font-semibold text-text-secondary'}>Map View</button><button onClick={() => setMode('list')} className={mode === 'list' ? 'rounded-md bg-primary px-4 py-2 text-xs font-semibold text-white' : 'rounded-md px-4 py-2 text-xs font-semibold text-text-secondary'}><List size={13} className="mr-1 inline" />List View</button></div>{mode === 'map' ? <div className="grid gap-5 lg:grid-cols-[1fr_300px]"><GeoMap fields={list} selected={activeSelected} onSelect={setSelected} /><Card><Wheat size={21} className="text-primary" /><h2 className="mt-4 text-lg font-bold">{activeSelected?.name}</h2><p className="mt-1 text-sm text-text-secondary">{activeSelected?.current_crop || 'Crop not recorded'} · {activeSelected?.area_acres} acres</p><div className="mt-5 space-y-3 border-y border-border py-4 text-sm"><p className="flex justify-between"><span className="text-text-secondary">Growth stage</span><b>{activeSelected?.current_stage || '—'}</b></p><p className="flex justify-between"><span className="text-text-secondary">Soil moisture</span><b>{activeSelected?.latest_moisture_percent == null ? '—' : String(activeSelected.latest_moisture_percent) + '%'}</b></p><p className="flex justify-between"><span className="text-text-secondary">Open alerts</span><b>{activeSelected?.alert_count ?? 0}</b></p></div><Link to={'/fields/' + activeSelected?.id} className="mt-5 flex items-center justify-between rounded-lg bg-primary px-4 py-2.5 text-xs font-semibold text-white">View field details <ChevronRight size={15} /></Link></Card></div> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{list.map((field) => <button className="rounded-card border border-border bg-white p-5 text-left shadow-card hover:border-primary" onClick={() => { setSelected(field); setMode('map'); }} key={field.id}><div className="flex justify-between"><div><p className="font-bold">{field.name}</p><p className="mt-1 text-xs text-text-secondary">{field.current_crop || 'Crop not recorded'} · {field.area_acres} acres</p></div><span className="rounded-full bg-primary-50 px-2 py-1 text-[10px] font-bold text-primary">{field.alert_count || 0} alerts</span></div><p className="mt-5 text-sm font-semibold text-primary-dark">{field.current_stage || 'No stage recorded'}</p><p className="mt-1 text-xs text-text-secondary">Moisture: {field.latest_moisture_percent == null ? '—' : String(field.latest_moisture_percent) + '%'}</p></button>)}</div>}</>}</Page>;
}

export function PestDisease() {
  const { fields } = useFarmData(); const [fieldId, setFieldId] = useState(fields[0]?.id || ''); const selectedFieldId = fieldId || fields[0]?.id || ''; const [file, setFile] = useState(null); const [result, setResult] = useState(null); const [error, setError] = useState(null); const [uploading, setUploading] = useState(false);
  const upload = async () => { if (!file) { setError(new Error('Choose a JPG, PNG, or WebP image first.')); return; } setUploading(true); setError(null); try { setResult(await farmStateApi.createDiagnosis(file, selectedFieldId)); } catch (err) { setError(err); } finally { setUploading(false); } };
  return <Page title="Pest & Disease" subtitle="Upload a real crop photo. The backend will show an explicit result or an inconclusive provider state."><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><Card><div className="flex min-h-72 flex-col items-center justify-center rounded-xl border-2 border-dashed border-primary-light bg-primary-50 p-6 text-center"><span className="grid size-14 place-items-center rounded-full bg-white text-primary shadow-card"><Camera size={26} /></span><h2 className="mt-4 font-bold">Upload a crop photo</h2><p className="mt-2 max-w-sm text-sm leading-6 text-text-secondary">No diagnosis is invented when a vision provider is unavailable.</p>{fields.length > 0 && <select value={fieldId} onChange={(event) => setFieldId(event.target.value)} className="mt-4 rounded-lg border border-border bg-white px-3 py-2 text-sm"><option value="">No field selected</option>{fields.map((field) => <option value={field.id} key={field.id}>{field.name}</option>)}</select>}<input id="diagnosis-file" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { setFile(event.target.files?.[0] || null); setResult(null); }} className="mt-4 block max-w-full text-xs" /><button onClick={upload} disabled={uploading} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Upload size={16} />{uploading ? 'Uploading…' : 'Upload photo'}</button>{error && <p className="mt-3 text-xs text-red-700">{error.message}</p>}</div></Card><Card><h2 className="font-bold">Photo tips</h2><ul className="mt-4 space-y-4 text-sm text-text-secondary"><li className="flex gap-2"><CheckCircle2 size={17} className="shrink-0 text-primary" />Use natural daylight.</li><li className="flex gap-2"><CheckCircle2 size={17} className="shrink-0 text-primary" />Keep the affected area in focus.</li><li className="flex gap-2"><CheckCircle2 size={17} className="shrink-0 text-primary" />Include leaf edges and both sides if possible.</li></ul></Card></div>{result && <Card className="mt-5 border-amber-200"><div className="flex items-start gap-3"><ScanSearch size={19} className="text-primary" /><div><p className="font-bold">{result.status === 'inconclusive' ? 'Diagnosis inconclusive' : result.label || 'Diagnosis result'}</p><p className="mt-2 text-sm leading-6 text-text-secondary">{result.error || 'The provider returned no additional explanation.'}</p><SourceStamp source={result.provider} fetchedAt={result.created_at} /></div></div></Card>}</Page>;
}

export function CropGuide() {
  const { fields } = useFarmData(); const [fieldId, setFieldId] = useState(fields[0]?.id || ''); const selectedFieldId = fieldId || fields[0]?.id || ''; const [cycles, setCycles] = useState([]); const [error, setError] = useState(null); const selected = fields.find((field) => field.id === selectedFieldId);
  useEffect(() => { if (!selectedFieldId) return; farmStateApi.getTimeline(selectedFieldId).then(setCycles).catch(setError); }, [selectedFieldId]); const cycle = cycles[0];
  return <Page title="Crop Guide" subtitle="Stage history and guidance from the selected field's recorded crop cycle.">{fields.length ? <select value={fieldId} onChange={(event) => setFieldId(event.target.value)} className="mb-5 rounded-lg border border-border bg-white px-3 py-2 text-sm">{fields.map((field) => <option value={field.id} key={field.id}>{field.name}</option>)}</select> : <EmptyState title="No fields" detail="Create a field first." />}{error && <ErrorState error={error} />}{cycle ? <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><Card><Sprout size={23} className="text-primary" /><h2 className="mt-4 font-bold">{selected?.name}</h2><p className="mt-1 text-sm text-text-secondary">{cycle.crop_name}</p><p className="mt-5 text-sm"><span className="text-text-secondary">Current stage</span><b className="ml-2 text-primary">{cycle.current_stage}</b></p></Card><div className="space-y-3">{cycle.stage_events.map((event) => <Card className={event.stage === cycle.current_stage ? 'border-primary bg-primary-50' : ''} key={event.id}><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-primary text-sm font-bold text-white">✓</span><div><h2 className="font-bold">{event.stage}</h2><p className="mt-1 text-sm text-text-secondary">Recorded on {new Date(event.occurred_at).toLocaleDateString()}</p>{event.note && <p className="mt-2 text-xs text-text-secondary">{event.note}</p>}</div></div></Card>)}</div></div> : fields.length > 0 && <EmptyState title="No crop cycle recorded" detail="Create a crop cycle through the Farm State API before using the live crop guide." />}</Page>;
}
