import { useState } from 'react';
import { ArrowRight, Droplets, Map, Plus, Sprout, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { farmImages } from '../data/images.js';
import { useLanguage } from '../hooks/useLanguage.jsx';
import { useFarmData } from '../context/FarmDataContext.jsx';
import { EmptyState, ErrorState, LoadingState } from '../components/feedback/ApiState.jsx';
import LocationPicker from '../components/fields/LocationPicker.jsx';

const cropImages = [farmImages.wheat, farmImages.potato, farmImages.mustard];

function approximateBoundary(latitude, longitude) {
  const lat = Number(latitude); const lon = Number(longitude); const delta = 0.001;
  return { type: 'Feature', properties: { quality: 'approximate_point_buffer' }, geometry: { type: 'Polygon', coordinates: [[[lon - delta, lat - delta], [lon + delta, lat - delta], [lon + delta, lat + delta], [lon - delta, lat + delta], [lon - delta, lat - delta]]] } };
}

function AddFieldDialog({ onClose, onCreate, profile }) {
  const [form, setForm] = useState({ name: '', area_acres: '', current_crop: '', latitude: profile?.latitude ?? '', longitude: profile?.longitude ?? '' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => {
    event.preventDefault(); setError('');
    if (form.latitude === '' || form.longitude === '') { setError('Latitude and longitude are required to create an approximate map boundary.'); return; }
    setSaving(true);
    try { await onCreate({ name: form.name, area_acres: Number(form.area_acres), current_crop: form.current_crop || null, boundary_geojson: approximateBoundary(form.latitude, form.longitude) }); onClose(); } catch (err) { setError(err.message); } finally { setSaving(false); }
  };
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/35 p-4"><div className="grid min-h-full place-items-center"><form onSubmit={submit} className="w-full max-w-2xl rounded-2xl border border-border bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Add field</h2><p className="mt-1 text-xs text-text-secondary">Choose the field location on the map. The first boundary is an explicitly approximate point buffer and can be surveyed later.</p></div><button type="button" onClick={onClose} aria-label="Close"><X size={20} /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Field name" className="rounded-lg border border-border px-3 py-2 text-sm" /><input required type="number" min="0.01" step="any" value={form.area_acres} onChange={(event) => update('area_acres', event.target.value)} placeholder="Area in acres" className="rounded-lg border border-border px-3 py-2 text-sm" /><input value={form.current_crop} onChange={(event) => update('current_crop', event.target.value)} placeholder="Current crop (optional)" className="rounded-lg border border-border px-3 py-2 text-sm sm:col-span-2" /></div><LocationPicker latitude={form.latitude} longitude={form.longitude} fallbackLocation={profile} onChange={(location) => setForm((current) => ({ ...current, latitude: location.latitude, longitude: location.longitude }))} />{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-800">{error}</p>}<button disabled={saving} className="mt-5 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Create field'}</button></form></div></div>;
}

export default function MyFields() {
  const { language } = useLanguage(); const hi = language === 'hi'; const { profile, fields, mapFields, loading, error, refresh, createField } = useFarmData(); const [showAdd, setShowAdd] = useState(false); const displayFields = fields.map((field) => ({ ...field, ...(mapFields.find((mappedField) => mappedField.id === field.id) || {}) }));
  const label = hi ? { title: 'मेरी फसलें', subtitle: 'अपने हर खेत की स्थिति और प्रगति देखें।', add: 'खेत जोड़ें', moisture: 'मिट्टी की नमी', details: 'खेत का विवरण देखें', mapTitle: 'अपने सभी खेत फार्म मैप पर देखें', mapText: 'एक ही जगह पर खेत की सीमा और स्वास्थ्य स्थिति देखें।', mapAction: 'फार्म मैप खोलें' } : { title: 'My Fields', subtitle: 'Track the health and progress of every field.', add: 'Add field', moisture: 'Soil moisture', details: 'View field details', mapTitle: 'See all fields on your farm map', mapText: 'View field boundaries and health status in one place.', mapAction: 'Open Farm Map' };
  return <div className="mx-auto max-w-[1440px] px-4 py-5 sm:px-6 lg:px-8 lg:py-7">
    {showAdd && <AddFieldDialog profile={profile} onClose={() => setShowAdd(false)} onCreate={createField} />}
    <header className="flex items-start justify-between"><div><h1 className="text-2xl font-bold">{label.title}</h1><p className="mt-1 text-sm text-text-secondary">{label.subtitle}</p></div><div className="flex gap-2"><Link to="/device-setup" className="rounded-lg border border-primary/25 bg-white px-3 py-2 text-xs font-semibold text-primary">Connect soil node</Link><button onClick={() => setShowAdd(true)} className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-white"><Plus size={15} />{label.add}</button></div></header>
    <div className="mt-6">{loading ? <LoadingState /> : error ? <ErrorState error={error} onRetry={refresh} /> : displayFields.length === 0 ? <EmptyState title="No fields yet" detail="Create your first field to unlock crop timelines, observations, alerts, and irrigation planning." action={<button onClick={() => setShowAdd(true)} className="mt-4 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-white">{label.add}</button>} /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{displayFields.map((field, index) => <article className="overflow-hidden rounded-card border border-border bg-white shadow-card" key={field.id}><img className="h-32 w-full object-cover" src={cropImages[index % cropImages.length]} alt="Field crop" /><div className="p-5"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><span className="rounded-lg bg-primary-50 p-1.5 text-primary"><Sprout size={15} /></span><h2 className="font-bold">{field.name}</h2></div><p className="mt-2 text-xs text-text-secondary">{field.current_crop || 'Crop not recorded'} · {field.area_acres} acres</p></div><span className="rounded-full bg-primary-50 px-2 py-1 text-[10px] font-bold text-primary">{field.status}</span></div><p className="mt-4 text-sm font-semibold text-primary-dark">{field.current_crop || 'No active crop cycle'}</p><div className="mt-2 flex items-center justify-between text-xs text-text-secondary"><span className="flex items-center gap-1"><Droplets size={14} className="text-info" />{label.moisture}</span><b>{field.latest_moisture_percent == null ? '—' : `${field.latest_moisture_percent}%`}</b></div><div className="mt-2 h-2 rounded-full bg-surface-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(field.latest_moisture_percent || 0, 100)}%` }} /></div><Link to={`/fields/${field.id}`} className="mt-5 flex items-center justify-between border-t border-border pt-4 text-xs font-semibold text-primary">{label.details}<ArrowRight size={15} /></Link></div></article>)}</div>}</div>
    <section className="mt-6 rounded-card border border-border bg-primary-50 p-5"><div className="flex items-start gap-3"><span className="rounded-lg bg-white p-2 text-primary"><Map size={21} /></span><div><h2 className="font-bold text-primary-dark">{label.mapTitle}</h2><p className="mt-1 text-sm text-text-secondary">{label.mapText}</p><Link className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-primary" to="/map">{label.mapAction}<ArrowRight size={15} /></Link></div></div></section>
  </div>;
}
