import { useState } from 'react';
import { Keyboard, Leaf, MapPin, Send, Volume2 } from 'lucide-react';
import VoiceButton from '../components/features/ai/VoiceButton.jsx';
import ConversationView from '../components/features/ai/ConversationView.jsx';
import { useAIConversation } from '../context/AIConversationContext.jsx';

const copy = { en: { badge: 'Voice-first assistant', title: 'Ask KisanSathi', intro: 'Speak naturally about your recorded fields. Audio is sent to the configured provider; unavailable providers stay explicit.', ready: 'Tap the microphone to speak', listening: 'Listening… speak now', processing: 'Processing audio…', responding: 'Response ready', placeholder: 'Or type your question…' }, hi: { badge: 'वॉइस सहायक', title: 'किसानसाथी से पूछें', intro: 'अपने रिकॉर्ड किए गए खेतों के बारे में सहजता से बोलें।', ready: 'बोलने के लिए माइक्रोफोन दबाएं', listening: 'सुन रहा हूं… अब बोलें', processing: 'ऑडियो संसाधित हो रहा है…', responding: 'उत्तर तैयार है', placeholder: 'या अपना सवाल लिखें…' }, mr: { badge: 'व्हॉइस सहाय्यक', title: 'किसानसाथीला विचारा', intro: 'तुमच्या नोंदवलेल्या शेताबद्दल सहज बोला.', ready: 'बोलण्यासाठी मायक्रोफोन दाबा', listening: 'ऐकत आहे… बोला', processing: 'ऑडिओवर प्रक्रिया सुरू आहे…', responding: 'उत्तर तयार आहे', placeholder: 'किंवा तुमचा प्रश्न लिहा…' } };

export default function VoiceAssistant() {
  const { language, voiceState, fields, selectedField, selectedFieldId, setSelectedFieldId, sendText, processing } = useAIConversation();
  const [input, setInput] = useState('');
  const c = copy[language] || copy.en;
  const status = voiceState === 'listening' ? c.listening : voiceState === 'processing' ? c.processing : voiceState === 'responding' ? c.responding : c.ready;
  const submit = (event) => { event.preventDefault(); if (input.trim()) { sendText(input); setInput(''); } };
  return <div className="mx-auto flex min-h-[calc(100svh-68px)] max-w-[1440px] flex-col px-4 py-5 sm:px-6 lg:px-8 lg:py-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-primary-50 px-3 py-1.5 text-xs font-semibold text-primary">{c.badge}</span><h1 className="mt-4 text-3xl font-bold">{c.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-text-secondary">{c.intro}</p></div><label className="text-xs font-semibold text-text-secondary">Field<select value={selectedFieldId} onChange={(event) => setSelectedFieldId(event.target.value)} className="mt-2 block rounded-lg border border-border bg-white px-3 py-2 text-sm">{fields.map((field) => <option value={field.id} key={field.id}>{field.name}</option>)}</select></label></div><div className="mt-6 grid min-h-[560px] gap-5 lg:grid-cols-[300px_1fr]"><aside className="flex flex-col items-center rounded-card border border-border bg-white p-6 text-center shadow-card"><span className="flex items-center gap-2 text-sm font-bold text-primary"><Leaf size={18} />{selectedField?.name || 'No field selected'}</span><span className="mt-8 grid size-9 place-items-center rounded-xl bg-primary text-white"><MapPin size={18} /></span><p className="mt-2 text-xs text-text-secondary">Field-aware conversation</p><VoiceButton large /><p className={`mt-5 text-sm font-semibold ${voiceState !== 'idle' ? 'text-primary' : 'text-text-secondary'}`}>{status}</p><div className="mt-6 flex items-start gap-2 rounded-xl bg-primary-50 p-4 text-left text-xs leading-5 text-primary-dark"><Volume2 size={17} className="mt-0.5 shrink-0" />Provider responses and transcript status are shown in the conversation.</div></aside><section className="flex min-h-0 flex-col"><ConversationView compact /><form onSubmit={submit} className="mt-4 flex gap-2 rounded-xl border border-border bg-white p-2 shadow-card"><Keyboard size={19} className="m-2 text-text-muted" /><input value={input} onChange={(event) => setInput(event.target.value)} placeholder={c.placeholder} className="min-w-0 flex-1 py-2 text-sm outline-none" /><button disabled={processing || !input.trim()} className="grid size-10 place-items-center rounded-lg bg-primary text-white disabled:opacity-50" aria-label="Send typed question"><Send size={17} /></button></form></section></div></div>;
}
