import { apiRequest, FARM_STATE_API_URL, queryString } from './client.js';

const request = (path, options = {}) => apiRequest(FARM_STATE_API_URL, path, { ...options, farmerScoped: true });

export const farmStateApi = {
  getStorageStatus: () => request('/v1/storage-status'),
  getDiagnostics: () => request('/v1/diagnostics'),
  listAuditEvents: (limit = 100) => request(`/v1/audit${queryString({ limit })}`),
  exportSnapshot: () => request('/v1/export'),
  getProfile: () => request('/v1/profile'), updateProfile: (body) => request('/v1/profile', { method: 'PUT', body }),
  listFields: () => request('/v1/fields'), createField: (body) => request('/v1/fields', { method: 'POST', body }),
  getField: (id) => request(`/v1/fields/${id}`), listMapFields: () => request('/v1/fields/map'),
  getTimeline: (id) => request(`/v1/fields/${id}/timeline`), getSoilHealth: (id) => request(`/v1/fields/${id}/soil-health`),
  getCropOptions: (id, { season, previousCrop, soilType } = {}) => request(`/v1/fields/${id}/crop-options${queryString({ season, previous_crop: previousCrop, soil_type: soilType })}`),
  getCropStageActionProposals: (id) => request(`/v1/fields/${id}/action-proposals`),
  getLatestObservations: (id) => request(`/v1/fields/${id}/observations/latest`),
  getObservationHistory: (id, measurement = 'moisture', limit = 24) => request(`/v1/fields/${id}/observations/history${queryString({ measurement, limit })}`),
  getWeather: (lat, lon) => request(`/v1/weather${queryString({ lat, lon })}`),
  getWeatherAlerts: (id) => request(`/v1/weather/alerts${queryString({ field_id: id })}`),
  getIrrigationPlan: (id) => request(`/v1/fields/${id}/irrigation-plan`),
  createIrrigationEvent: (body) => request('/v1/irrigation-events', { method: 'POST', body }),
  listIrrigationEvents: (fieldId, limit = 30) => request(`/v1/irrigation-events${queryString({ field_id: fieldId, limit })}`),
  createReminder: (body) => request('/v1/reminders', { method: 'POST', body }), listReminders: () => request('/v1/reminders'),
  listFieldTasks: (fieldId, status) => request(`/v1/tasks${queryString({ field_id: fieldId, status })}`),
  createFieldTask: (body) => request('/v1/tasks', { method: 'POST', body }),
  updateFieldTaskStatus: (id, status) => request(`/v1/tasks/${id}`, { method: 'PATCH', body: { status } }),
  listLedgerEntries: (entryType, status = 'active', fieldId) => request(`/v1/ledger/entries${queryString({ entry_type: entryType, status, field_id: fieldId })}`),
  getLedgerSummary: () => request('/v1/ledger/summary'),
  createLedgerEntry: (body) => request('/v1/ledger/entries', { method: 'POST', body }),
  updateLedgerEntryStatus: (id, status) => request(`/v1/ledger/entries/${id}`, { method: 'PATCH', body: { status } }),
  listAlerts: (status) => request(`/v1/alerts${queryString({ status })}`), updateAlert: (id, status) => request(`/v1/alerts/${id}`, { method: 'PATCH', body: { status } }),
  getDashboard: () => request('/v1/dashboard'), createDiagnosis: (file, fieldId, confirmedCrop) => { const form = new FormData(); form.append('file', file); if (fieldId) form.append('field_id', fieldId); if (confirmedCrop) form.append('confirmed_crop', confirmedCrop); return request('/v1/diagnoses', { method: 'POST', body: form, timeoutMs: 30000 }); },
  createDiagnosisFeedback: (diagnosisId, body) => request(`/v1/diagnoses/${diagnosisId}/feedback`, { method: 'POST', body }),
  getDiagnosis: (id) => request(`/v1/diagnoses/${id}`), createAdvisorSession: (body) => request('/v1/advisor/sessions', { method: 'POST', body }),
  sendAdvisorMessage: (id, body) => request(`/v1/advisor/sessions/${id}/messages`, { method: 'POST', body }),
  sendVoiceTurn: (blob) => request('/v1/voice/turns', { method: 'POST', body: blob, headers: { 'Content-Type': blob.type || 'audio/webm' }, timeoutMs: 30000 }),
  transcribeVoice: (blob, languageCode) => request(`/v1/voice/transcribe${queryString({ language_code: languageCode })}`, { method: 'POST', body: blob, headers: { 'Content-Type': blob.type || 'audio/webm' }, timeoutMs: 30000 }),
  synthesizeSpeech: (body) => request('/v1/voice/synthesize', { method: 'POST', body, timeoutMs: 30000 }),
  translateText: (body) => request('/v1/translate', { method: 'POST', body, timeoutMs: 30000 }),
  getSarvamRuntimeConfig: () => request('/v1/sarvam/runtime-config'),
  updateSarvamRuntimeConfig: (body) => request('/v1/sarvam/runtime-config', { method: 'PUT', body }),
  createReport: (body) => request('/v1/reports', { method: 'POST', body }), listReports: () => request('/v1/reports'),
};

