/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState } from 'react'
import { fields, localizeField } from '../data/fields.js'
import { useLanguage } from '../hooks/useLanguage.jsx'

const AIConversationContext = createContext(null)

const now = () => new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
const replies = {
  en: { health: 'Your wheat is in the Grain Filling stage. The yellowing could be nutrient stress or low moisture. Please share a clear leaf photo so I can guide you accurately.', irrigation: 'Soil moisture is low at 28%. Plan irrigation within 1–2 days, preferably between 6 and 10 AM.', generic: 'Based on your field data, keep soil moisture steady and inspect the crop again after irrigation.', image: 'I can help identify the visible symptoms. Please upload a clear photo of the affected leaf.', confirm: 'Would you like to mark irrigation as planned for your wheat field?' }, hi: { health: 'आपकी गेहूं की फसल दाना भराव अवस्था में है। पत्तियों का पीला पड़ना पोषण या कम नमी का संकेत हो सकता है। सही सलाह के लिए पत्ती की साफ फोटो भेजें।', irrigation: 'मिट्टी की नमी 28% है, जो कम है। अगले 1–2 दिनों में सुबह 6 से 10 बजे के बीच सिंचाई करें।', generic: 'आपके खेत की जानकारी के अनुसार मिट्टी में नमी बनाए रखें और सिंचाई के बाद फसल की फिर से जांच करें।', image: 'दिख रहे लक्षणों की पहचान के लिए पत्ती की साफ फोटो भेजें।', confirm: 'क्या आप अपने गेहूं के खेत के लिए सिंचाई की योजना की पुष्टि करना चाहते हैं?' }, mr: { health: 'तुमचे गहू पीक दाणे भरण्याच्या अवस्थेत आहे. पिवळेपणा पोषणाची कमतरता किंवा कमी ओलाव्याचे लक्षण असू शकते. अचूक सल्ल्यासाठी पानाचा स्पष्ट फोटो पाठवा.', irrigation: 'मातीचा ओलावा 28% असून कमी आहे. पुढील 1–2 दिवसांत सकाळी 6 ते 10 दरम्यान सिंचन करा.', generic: 'तुमच्या शेताच्या माहितीनुसार मातीतील ओलावा टिकवा आणि सिंचनानंतर पिकाची पुन्हा तपासणी करा.', image: 'दिसत असलेल्या लक्षणांची ओळख करण्यासाठी पानाचा स्पष्ट फोटो पाठवा.', confirm: 'तुमच्या गहू शेतासाठी सिंचनाची योजना निश्चित करायची आहे का?' } }

export function AIConversationProvider({ children }) {
  const { language } = useLanguage()
  const [messages, setMessages] = useState([{ id: 1, role: 'assistant', text: replies.en.health, time: '10:31 AM' }])
  const [voiceState, setVoiceState] = useState('idle')
  const [selectedFieldId, setSelectedFieldId] = useState(fields[0].id)
  const [pendingAction, setPendingAction] = useState(null)
  const [processing, setProcessing] = useState(false)
  const localizedFields = fields.map(item => localizeField(item, language))
  const selectedField = localizedFields.find(item => item.id === selectedFieldId) || localizedFields[0]
  const addAssistant = (text, action) => { const message = { id: Date.now() + Math.random(), role: 'assistant', text, time: now(), action }; setMessages(current => [...current, message]); if (action) setPendingAction(action); return message }
  const replyFor = text => { const q = text.toLowerCase(); if (q.includes('photo') || q.includes('image') || q.includes('फोटो') || q.includes('तस्वीर')) return { text: replies[language].image, action: { type: 'image_upload' } }; if (q.includes('irrigat') || q.includes('सिंचाई') || q.includes('पानी') || q.includes('पाणी')) return { text: replies[language].confirm, action: { type: 'confirmation', title: language === 'hi' ? 'सिंचाई की पुष्टि' : language === 'mr' ? 'सिंचनाची पुष्टी' : 'Confirm irrigation', confirmLabel: language === 'hi' ? 'सिंचाई की योजना बनाएं' : language === 'mr' ? 'सिंचन नियोजित करा' : 'Plan irrigation' } }; if (q.includes('health') || q.includes('yellow') || q.includes('पीला') || q.includes('पीले') || q.includes('पिवळ')) return { text: replies[language].health }; return { text: replies[language].generic } }
  const sendText = text => { const content = text.trim(); if (!content) return; setMessages(current => [...current, { id: Date.now(), role: 'user', text: content, time: now() }]); setProcessing(true); setTimeout(() => { const reply = replyFor(content); addAssistant(reply.text, reply.action); setProcessing(false) }, 450) }
  const startVoice = () => { if (voiceState !== 'idle') return; setVoiceState('listening'); setTimeout(() => { setVoiceState('processing'); setTimeout(() => { const query = language === 'hi' ? 'मेरी गेहूं की फसल कैसी है?' : language === 'mr' ? 'माझ्या गव्हाच्या पिकाची स्थिती कशी आहे?' : 'How is my wheat crop doing?'; setMessages(current => [...current, { id: Date.now(), role: 'user', text: query, time: now(), via: 'voice' }]); setVoiceState('responding'); addAssistant(replies[language].health); setTimeout(() => setVoiceState('idle'), 700) }, 650) }, 850) }
  const cancelVoice = () => setVoiceState('idle')
  const submitImage = file => { const image = URL.createObjectURL(file); setMessages(current => [...current, { id: Date.now(), role: 'user', text: language === 'hi' ? 'मैंने फसल की फोटो अपलोड की है।' : language === 'mr' ? 'मी पिकाचा फोटो अपलोड केला आहे.' : 'I uploaded a crop photo.', time: now(), image }]); setPendingAction(null); addAssistant(language === 'hi' ? 'फोटो मिल गई। यह शुरुआती एफिड संक्रमण जैसा लग रहा है। सुबह नीम तेल का छिड़काव करने से पहले पास की पत्तियों की जांच करें।' : language === 'mr' ? 'फोटो मिळाला. हे सुरुवातीच्या मावा किडीच्या प्रादुर्भावासारखे दिसते. सकाळी निंबोळी तेल फवारण्यापूर्वी जवळची पाने तपासा.' : 'Photo received. This looks like an early aphid infestation. Inspect nearby leaves before applying neem oil in the morning.') }
  const resolveConfirmation = confirmed => { setPendingAction(null); addAssistant(confirmed ? (language === 'hi' ? 'सिंचाई योजना दर्ज कर दी गई है। सुबह जल्दी पानी देना सबसे अच्छा रहेगा।' : language === 'mr' ? 'सिंचन योजना नोंदवली आहे. सकाळी लवकर पाणी देणे उत्तम राहील.' : 'Irrigation has been marked as planned. Early morning is the best time to water.') : (language === 'hi' ? 'कोई सिंचाई योजना दर्ज नहीं की गई। आप कभी भी दोबारा पूछ सकते हैं।' : language === 'mr' ? 'सिंचन योजना नोंदवली नाही. तुम्ही कधीही पुन्हा विचारू शकता.' : 'No irrigation plan was recorded. You can ask again whenever you are ready.')) }
  const value = { messages, voiceState, processing, selectedField, localizedFields, setSelectedFieldId, sendText, startVoice, cancelVoice, pendingAction, submitImage, resolveConfirmation, language }
  return <AIConversationContext.Provider value={value}>{children}</AIConversationContext.Provider>
}
export function useAIConversation() { const context = useContext(AIConversationContext); if (!context) throw new Error('useAIConversation must be used inside AIConversationProvider'); return context }
